# todo pull a file from github and run it here
import urllib.request
import LaptopToComp
import send2trash
import time
from github import Github
import base64
import pygit2
import shutil
import os
# codeshare.com also can
# TODO all the RSNA stuff should actually be kept in either FDrive or the cloud. If inaccessible from Fdrive, use the cloud.
# TODO all the RSNA data should be in here

# or can use jupyter
# pretty sure this whole thing can just be done on jupyter
# just write the code here then copy paste.
# don't run the exact same file on the comp, it will be an imported module within the same folder,
# ... then there should be another file running in jupyter on the com periodically calling the one made by laptop
# then can catch the errors that come when the file from the laptop doesn't exist yet

# TODO shove all of this inside a while loop that has a try except thing for when the module from the laptop isn't there



g = Github("AshwinKurup", "1Ashwin_Kurup1")

























# TODO the credentials expired for some reason- probably cos i shoved it back onto github







print(g.get_user())
repo = g.get_user().get_repo("LaptopToComp")
file_content = repo.get_contents('test1.py')
file_data = base64.b64decode(file_content.content)
print(file_data)
#f= open("LaptopCode.py","w+")
#f.write(file_data)


#repoClone = pygit2.clone_repository(repo.git_url, 'C:\\Users\\Ashok\\Documents\\GitHub\\CompFromLaptop\\LAPTOPCODE') # this creates a repo, btw



# TODO if dk how to use the a python file from a different directory, just copy it over to this one lol
# newPath = shutil.copy('C:\\Users\\Kurup\Miniconda3\\Lib\\site-packages\\vizdoom\\examples\\ClonedRepo\\test1.py',
#                       'C:\\Users\\Kurup\Miniconda3\\Lib\\site-packages\\vizdoom\\examples\\CompFromLaptop')
# today use this for MNIST
# TODO IF IF IF IF IF I am unable to remove the current directory, is cool, make a dict with a million names generated by a list, then assign a new one to the repo each time.
send2trash.send2trash('C:\\Users\\Ashok\\Documents\\GitHub\\CompFromLaptop\\LAPTOPCODE')
# THIS WORKS